### ISSUE TITLE
Edit metadata whilst data is uploading

### ISSUE THREAD

**Issue by lgilies** [datopian/datapub#11] opened 2020-08-11 10:58 UTC
When the upload is in progress the metadata fields (Title, description, encode, format) the metadata information should be editable at the same moment of the upload.

## Acceptance

* [ ]   Metadata fields (title, description, encode, and format) editable when the file is uploading.

## Tasks

* [ ] UI - Enable metadata fields(title, description, encode, and format) when the file is uploading.
* [ ] JS - Get the new values from the metadata fields and update the information.

**Comment by rufuspollock** [comment] 2020-08-24 14:24
DUPLICATE of #12 (now).

**Closed by rufuspollock** 2020-08-24 14:24 UTC
